#!/bin/sh

if [ "$1" ]; then
    #string:x-canonical-private-synchronous:anything makes notification replace previous one
    notify-send -a "mywob" " " -i I -h int:value:"$1" -h string:synchronous:volume -h string:x-canonical-private-synchronous:anything -t 1000

fi
